version: 1
runtime:
  log_level: INFO
  reconnect_backoff_s: [1, 2, 5, 10, 20]
  heartbeat_interval_s: 20
symbols:
  - R_10
  - R_25
  - R_50
  - R_75
  - R_100

# Historical fetch mode for long horizon
historical_mode: candles

# Whether to also fetch last 5000 ticks at startup
bootstrap_ticks: true

# Interval in seconds between merge/features/validation cycles
merge_interval_seconds: 60

#enable phase 2
phase2_enabled: true

#enable phase 3

simulator:
  enabled: true
  mode: "hybrid"          # "parametric", "bootstrap", or "hybrid"
  count: 1000             # number of synthetic ticks per run
  mixture_components: 3   # for parametric/hybrid
  bootstrap_block: 5      # block size for bootstrap
  noise_scale: 0.08       # for hybrid FFT noise
  seed: 42
  min_records: 500

#enable drift phase 4

drift:
  enabled: true
  cadence_seconds: 1800
  min_records: 500
  kl_threshold: 0.1
  ks_p_threshold: 0.01
  autocorr_threshold: 0.05
  fft_threshold: 0.05

#enable phase 5
hardening:
  enabled: true
  count: 1000
  mode: "hybrid"
  mixture_components: 2
  bootstrap_block: 5
  noise_scale: 0.1
  seed: 42
  min_records: 500
  auc_threshold: 0.6


#enable 7th phase
fingerprinting:
  enabled: true
  count: 1000
  mode: "hybrid"
  mixture_components: 2
  bootstrap_block: 5
  noise_scale: 0.1
  seed: 42
  min_records: 500
  tolerance: 0.05

  
io:
  flush_interval_s: 5
  max_buffer: 5000
  format: csv
trainer:
  min_shard_ticks: 5000
  epochs: 1
